# Generated by Django 4.1.1 on 2022-10-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="create_at", new_name="created_at",
        ),
        migrations.RenameField(
            model_name="question", old_name="create_at", new_name="created_at",
        ),
    ]
