# Generated by Django 4.1.1 on 2022-10-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_answer_author_question_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modified_at",
            field=models.DateField(auto_now=True, verbose_name="수정 날짜"),
        ),
        migrations.AddField(
            model_name="question",
            name="modified_at",
            field=models.DateField(auto_now=True, verbose_name="수정 날짜"),
        ),
    ]
