# Generated by Django 4.1.1 on 2022-09-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_runner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runner", name="name", field=models.CharField(max_length=60),
        ),
        migrations.AlterModelTable(name="runner", table="runner",),
    ]
