# Generated by Django 4.1.1 on 2022-09-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0007_alter_runner_name_alter_runner_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="medal",
            field=models.CharField(
                blank=True,
                choices=[("GOLD", "Gold"), ("SIVER", "Siver"), ("BRONZE", "Bronze")],
                max_length=10,
            ),
        ),
    ]
