# Generated by Django 4.1.1 on 2022-09-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0009_fruit"),
    ]

    operations = [
        migrations.AlterModelTable(name="fruit", table="fruit",),
    ]
